image: gradle:8-jdk-21-and-23 # Specify the Gradle image with a compatible JDK version

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"  # Disable the Gradle daemon for CI builds

stages:
  - test
  - build

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .gradle/wrapper/
    - .gradle/caches/

before_script:
  - gradle --version  # Check Gradle and Java versions
  - chmod +x gradlew  # Ensure the Gradle wrapper is executable

build:
  stage: build
  tags:
    - comp2013_2024_cwk_part2
  script:
    - ./gradlew clean build  # Build the project using Gradle
  artifacts:
    paths:
      - build/libs/  # Save the built JAR files as artifacts
    expire_in: 1 week

test:
  stage: test
  tags:
    - comp2013_2024_cwk_part2
  script:
    - ./gradlew test  # Run unit tests using Gradle
  artifacts:
    reports:
      junit: build/test-results/**/*.xml  # Save test results in JUnit format
    paths:
      - build/reports/tests/test/  # Save the test reports
    expire_in: 1 week